name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install pnpm
        uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
        with:
          version: 10
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - run: pnpm lint && pnpm fmt
      - name: Check hash
        id: check_hash
        uses: ./.github/actions/check-dist-manifest
      - name: Comment on PR if no changes
        if: github.event_name == 'pull_request' && steps.check_hash.outputs.is-dirty == 'false'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body ":fast_forward: Merging this PR will have no impact on the live site as the build output remains unchanged."
